name: Linux BIN

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup GraalVM environment
      uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: '21.2.0.java11'
    - name: APT update
      run: sudo apt update  
    - name: Install libraries
      run: sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev
    
    - name: build modules
      run: mvn -P fast install
      
    - name: gluonfx plugin build
      run: mvn -f ./deploy/graalvm/pom.xml clean package gluonfx:build
      env:
        GRAALVM_HOME: ${{ env.JAVA_HOME }}    
    
    - name: Make staging directory
      run: mkdir staging
    - name: Copy native client to staging
      run: cp -r ./deploy/graalvm/target/gluonfx/x86_64-linux/OpenJfxJcrBrowser* staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: linux_binary
        path: staging
