# This workflow will build a .deb installer
name: Linux DEB/RPM installers, executable jars (platform dependent)

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: Build modules
      run: mvn -P fast install
      
    - name: Build with Maven
      run: mvn -f ./deploy/jpackagefx/pom.xml package
      
    - name: Make deb-staging directory
      run: mkdir deb-staging
    - name: Copy native .deb to staging
      run: cp -r ./deploy/jpackagefx/target/installer/*.deb deb-staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: linux .deb installer
        path: deb-staging
        
    - name: Make rpm-staging directory
      run: mkdir rpm-staging
    - name: Copy native .rpm to staging
      run: cp -r ./deploy/jpackagefx/target/installer/*.rpm rpm-staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: linux .rpm installer
        path: rpm-staging    
        
    - name: Build plain fat/uber jars
      run: mvn -f ./deploy/spring-boot-maven/pom.xml package    
    - name: upload platform dependent fat/uber jars
      run: mkdir jar-staging
    - name: Copy JARs to staging
      run: cp ./deploy/spring-boot-maven/target/*.jar jar-staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: excecuteable jars linux
        path: jar-staging
