# This workflow will build a .deb installer
name: Mac PKG/DMG installers, executable jars (platform dependent)

on:
  workflow_dispatch

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '11.7.0'
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Maven
      run: mvn -P build-mac package
      
      
    # upload pkg
    - name: Make pkg-staging director
      run: mkdir pkg-staging
    - name: Copy native msi to staging
      run: cp -r target/installer/*.pkg pkg-staging     
    - name: Upload pkg
      uses: actions/upload-artifact@v2
      with:
        name: mac .pkg installer
        path: pkg-staging    
        
    # upload dmg    
    - name: Make dmg-staging director
      run: mkdir dmg-staging  
    - name: Copy native dmg to staging
      run: cp -r target/installer/*.dmg dmg-staging    
    - name: Upload dem
      uses: actions/upload-artifact@v2
      with:
        name: mac .dmg installer
        path: dmg-staging
    
    # executable jars (platform dependent)    
    - name: Platform dependent fat/uber jars
      run: mkdir jar-staging
    - name: Copy JARs to staging
      run: cp target/*.jar staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: excecuteable jars mac
        path: jar-staging
