name: MacOS BIN

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v3
    - uses: gluonhq/setup-graalvm@master
      # set GITHUB_TOKEN to avoid exceeding GitHub's API rate limit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # GraalVM version. Default: latest
        graalvm: '22.1.0.1-Final'
        # Java version. Since GraalVM 22, either java11 or java17, before GraalVM 22, empty. Default: java17
        jdk: 'java17'

    - run: java -version
    
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.8
        
    - name: build modules
      run: mvn -P fast install
      
    - name: Make staging directory
      run: mkdir staging
    
    - name: gluonfx plugin build
      run: mvn -f ./deploy/graalvm/pom.xml clean package gluonfx:build
      env:
        GRAALVM_HOME: ${{ env.JAVA_HOME }}
        
    - name: Copy native client to staging
      run: cp -r ./deploy/graalvm/target/gluonfx/x86_64-darwin/OpenJfxJcrBrowser* staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: mac_binary
        path: staging
