# This workflow will build a .deb installer
name: Mac PKG/DMG installers, executable jars

on:
  workflow_dispatch

jobs:
  build:

    runs-on: macOS-12
    
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: Build modules
      run: mvn -P fast install
      
    - name: Build with Maven
      run: mvn -f ./deploy/jpackagefx/pom.xml package
      
      
    # upload pkg
    - name: Make pkg-staging directory
      run: mkdir pkg-staging
    - name: Copy native pkg to staging
      run: cp -r ./deploy/jpackagefx/target/installer/*.pkg pkg-staging     
    - name: Upload pkg
      uses: actions/upload-artifact@v2
      with:
        name: mac .pkg installer
        path: pkg-staging    
        
    # upload dmg    
    - name: Make dmg-staging directory
      run: mkdir dmg-staging  
    - name: Copy native dmg to staging
      run: cp -r ./deploy/jpackagefx/target/installer/*.dmg dmg-staging    
    - name: Upload dem
      uses: actions/upload-artifact@v2
      with:
        name: mac .dmg installer
        path: dmg-staging
        
    - name: Build plain fat/uber jars
      run: mvn clean package    
    
    # Excecuteable jars    
    - name: Build plain spring-boot fat-jar
      run: mvn -f ./deploy/spring-boot-maven/pom.xml package    
    - name: upload platform dependent fat/uber jars
      run: mkdir jar-staging
    - name: Copy JARs to staging
      run: cp ./deploy/spring-boot-maven/target/*-fat.jar jar-staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Excecuteable spring-boot jar for mac
        path: jar-staging
        
    - name: Build plain maven-shade uber-jar
      run: mvn -f ./deploy/maven-shade/pom.xml package    
    - name: upload platform dependent uber jar
      run: mkdir maven-shade-staging
    - name: Copy JARs to maven-shade-staging
      run: cp ./deploy/spring-boot-maven/target/*-fat.jar maven-shade-staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Excecuteable maven-shaded jar for mac
        path: maven-shade-staging    
