name: MacOS BIN

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '11.7.0'
    - uses: actions/checkout@v2
    - name: Setup GraalVM environment
      uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: '21.2.0.java11'
    
    - name: build modules
      run: mvn -P fast install
      
    - name: Make staging directory
      run: mkdir staging
    
    - name: gluonfx plugin build
      run: mvn -f ./deploy/graalvm/pom.xml clean package gluonfx:build
      env:
        GRAALVM_HOME: ${{ env.JAVA_HOME }}
        
    - name: Copy native client to staging
      run: cp -r ./deploy/graalvm(target/client/x86_64-darwin/OpenJfxJcrBrowser* staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: mac_binary
        path: staging
