# This workflow will build a .deb installer
name: Web-based deployments, JNLP/JPRO

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: Build modules
      run: mvn -P fast install
      
    - name: Build webstart zip with signed jars
      run: mvn -f ./deploy/webstart/pom.xml package
      
    - name: Make webstart-staging directory
      run: mkdir webstart-staging
    - name: Copy native .deb to staging
      run: cp -r ./deploy/webstart/target*.zip webstart-staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: webstart zip (needs edit of jnlp inside)
        path: webstart-staging
        
    - name: Build jpro zip with server
      run: mvn -f ./deploy/jpro/pom.xml jpro:release
    