# This workflow will build a .deb installer
name: Windows .msi installer with jpackage

on:
  workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with jpackage scripts
      run: mvn -P build-win package
    
    - name: Make staging directory
      run: mkdir staging
    - name: Copy native msi to staging
      run: cp -r target/installer/*.msi staging
    - name: Copy native exe to staging
      run: cp -r target/installer/*.exe staging  
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: windows installer
        path: staging    
