name: Windows EXE

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v1
      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '21.0.0.java11'
      - name: Make staging directory
        run: mkdir staging
      - name: gluon client plugin build
        run: mvn -P spring-graal client:build
        env:
          GRAALVM_HOME: ${{ env.JAVA_HOME }}
      - name: Copy native client to staging
        run: cp -r target/client/x86_64-windows/*.exe staging
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: windows_exe
          path: staging
