# This workflow will build a .deb installer
name: Windows MSI/EXE installers, executable jars

on:
  workflow_dispatch

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: build modules
      run: mvn -P fast install
      
    - name: Build with jpackage scripts
      working-directory: ./deploy/jpackagefx
      run: mvn package
    
    # upload msi
    - name: Make msi-staging directory
      run: mkdir msi-staging
    - name: Copy native msi to staging
      run: cp -r ./deploy/jpackagefx/target/installer/*.msi msi-staging     
    - name: Upload msi
      uses: actions/upload-artifact@v2
      with:
        name: windows msi installer
        path: msi-staging    
        
    # upload setup.exe    
    - name: Make exe-staging directory
      run: mkdir exe-staging  
    - name: Copy native exe to staging
      run: cp -r ./deploy/jpackagefx/target/installer/*.exe exe-staging    
    - name: Upload setup exe
      uses: actions/upload-artifact@v2
      with:
        name: windows setup.exe style installer
        path: exe-staging
        
    # Excecuteable jars    
    - name: Build plain spring-boot fat-jar
      run: mvn -f ./deploy/spring-boot-maven/pom.xml package    
    - name: upload platform dependent fat/uber jars
      run: mkdir jar-staging
    - name: Copy JARs to staging
      run: cp ./deploy/spring-boot-maven/target/*-fat.jar jar-staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Excecuteable spring-boot jar for windows
        path: jar-staging
        
    - name: Build plain maven-shade uber-jar
      run: mvn -f ./deploy/maven-shade/pom.xml package    
    - name: upload platform dependent uber jar
      run: mkdir maven-shade-staging
    - name: Copy JARs to maven-shade-staging
      run: cp ./deploy/spring-boot-maven/target/*-fat.jar maven-shade-staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Excecuteable maven-shaded jar for windows
        path: maven-shade-staging     
