name: Windows EXE

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v1
      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '21.2.0.java11'
      
      - name: build modules
        run: mvn -P fast install
        
      - name: Make staging directory
        run: mkdir staging
        
      - name: gluonfx plugin build
        run: mvn -f ./deploy/graalvm/pom.xml clean package gluonfx:build
        env:
          GRAALVM_HOME: ${{ env.JAVA_HOME }}
          
      - name: Copy native client to staging
        run: cp -r ./deploy/graalvm/target/gluonfx/x86_64-windows/*.exe staging
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: windows_exe
          path: staging
