# This workflow will build a .deb installer
name: Windows MSI/EXE installers, executable jars (platform dependent)

on:
  workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with jpackage scripts
      run: mvn -P build-win package
    
    # upload msi
    - name: Make msi-staging directory
      run: mkdir msi-staging
    - name: Copy native msi to staging
      run: cp -r target/installer/*.msi msi-staging     
    - name: Upload msi
      uses: actions/upload-artifact@v2
      with:
        name: windows msi installer
        path: msi-staging    
        
    # upload setup.exe    
    - name: Make exe-staging directory
      run: mkdir exe-staging  
    - name: Copy native exe to staging
      run: cp -r target/installer/*.exe exe-staging    
    - name: Upload setup exe
      uses: actions/upload-artifact@v2
      with:
        name: windows setup.exe style installer
        path: exe-staging
        
    - name: Build plain fat/uber jars
      run: mvn clean package    
    # executable jars (platform dependent)    
    - name: Platform dependent fat/uber jars
      run: mkdir jar-staging
    - name: Copy JARs to staging
      run: cp target/*.jar staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: excecuteable jars mac
        path: jar-staging
